name: Build & Push Prometheus image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]   # tag releases like v1.0.0 to produce versioned images
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: docker-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Validate your Prometheus config before building
      - name: Validate prometheus.yml with promtool
        run: |
          docker run --rm \
            -v "$PWD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro" \
            prom/prometheus:latest \
            promtool check config /etc/prometheus/prometheus.yml

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Generate tags & labels automatically:
      #  - latest on default branch
      #  - sha tag on every push
      #  - v* tag when pushing a git tag
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/prometheus-monitor
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=ref,event=tag

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
