name: Validate Docker Compose file

on:
  push:
    branches: [ main ]

jobs:
  validate-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Validate docker-compose.yml
        run: docker compose -f docker-compose.yml config
